RealProperty/Controllers/ProvinceController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RealProperty.Domain.Models;

namespace RealProperty.Controllers
{
    [Authorize(Roles = "Superman")]
    public class ProvinceController : Controller
    {
        private RealPropertyContext db = new RealPropertyContext();

        //
        // GET: /Province/

        public ActionResult Index()
        {
            return View(db.Provinces.ToList());
        }

        //
        // GET: /Province/Details/5

        public ActionResult Details(int id = 0)
        {
            Province province = db.Provinces.Find(id);
            if (province == null)
            {
                return HttpNotFound();
            }
            ViewBag.CountryId = new SelectList(db.Countries, "CountryId", "Name", province.CountryId);
            return View(province);
        }

        //
        // GET: /Province/Create

        public ActionResult Create()
        {
            ViewBag.CountryId = new SelectList(db.Countries, "CountryId", "Name");
            return View();
        }

        //
        // POST: /Province/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Province province)
        {
            if (ModelState.IsValid)
            {
                db.Provinces.Add(province);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CountryId = new SelectList(db.Countries, "CountryId", "Name", province.CountryId);
            return View(province);
        }

        //
        // GET: /Province/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Province province = db.Provinces.Find(id);
            if (province == null)
            {
                return HttpNotFound();
            }
            ViewBag.CountryId = new SelectList(db.Countries, "CountryId", "Name", province.CountryId);
            return View(province);
        }

        //
        // POST: /Province/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Province province)
        {
            if (ModelState.IsValid)
            {
                db.Entry(province).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CountryId = new SelectList(db.Companies, "CountryId", "Name", province.CountryId);
            return View(province);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

RealProperty/Views/Province/Create.cshtml
@using RealProperty.HtmlHelpers;
@model RealProperty.Domain.Models.Province

@{
    ViewBag.Title = "Create Province";
}

@section actions {
    <p>
        <a href="@Url.Action("Index", "Province")" class="btn btn-info btn-block"> <i class="icon-edit"></i> Cancel</a>
    </p>
}

<div class="container">
    @using (Html.BeginForm("Create", "Province", FormMethod.Post, htmlAttributes: new { @class = "form-horizontal", @role = "form" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, message: null, htmlAttributes: new { @class = "alert alert-danger" })

        <div class="row">
            <div class="col-lg-6">
                <div class="form-group @Html.FormControlValidatorClassFor(model => model.CountryId)">
                    @Html.LabelFor(model => model.CountryId, "Country" , htmlAttributes: new { @class = "control-label" })
                    @Html.DropDownListFor(model => model.CountryId, null, htmlAttributes: new { @class = "form-control", @placeholder = "Country" })
                    @Html.ValidationMessageFor(model => model.CountryId, validationMessage: null, htmlAttributes: new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6">
                <div class="form-group @Html.FormControlValidatorClassFor(model => model.Description)">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label" })
                    @Html.TextBoxFor(model => model.Description, htmlAttributes: new { @class = "form-control", @placeholder = "Description", @autofocus = "" })
                    @Html.ValidationMessageFor(model => model.Description, validationMessage: null, htmlAttributes: new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-2">
                <div class="form-group">
                    <input type="submit" class="btn btn-success btn-lg btn-block" value="Save" />
                </div>
            </div>
        </div>
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RealProperty/Views/Province/Details.cshtml
@model RealProperty.Domain.Models.Province

@{
    ViewBag.Title = "Province Details";
}

@section actions {
    <p>
        <a href="@Url.Action("Index", "Province")" class="btn btn-success btn-block"> <i class="icon-edit"></i> Home</a>
    </p>
}

<div class="container">
    <fieldset disabled>
        <div class="row">
            <div class="col-lg-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.CountryId, "Country", htmlAttributes: new { @class = "control-label" })
                    @Html.DropDownListFor(model => model.CountryId, null, htmlAttributes: new { @class = "form-control", @placeholder = "Country" })
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label" })
                    @Html.TextBoxFor(model => model.Description, htmlAttributes: new { @class = "form-control" })
                </div>
            </div>
        </div>
    </fieldset>
</div>

RealProperty/Views/Province/Edit.cshtml
@using RealProperty.HtmlHelpers;
@model RealProperty.Domain.Models.Province

@{
    ViewBag.Title = "Edit Province";
}

@section actions {
    <p>
        <a href="@Url.Action("Index", "Province")" class="btn btn-info btn-block"> <i class="icon-edit"></i> Cancel</a>
    </p>
}

<div class="container">
    @using (Html.BeginForm("Edit", "Province", FormMethod.Post, htmlAttributes: new { @class = "form-horizontal", @role = "form" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, message: null, htmlAttributes: new { @class = "alert alert-danger" })

        @Html.HiddenFor(model => model.ProvinceId)
        <div class="row">
            <div class="col-lg-6">
                <div class="form-group @Html.FormControlValidatorClassFor(model => model.CountryId)">
                    @Html.LabelFor(model => model.CountryId, "Country" , htmlAttributes: new { @class = "control-label" })
                    @Html.DropDownListFor(model => model.CountryId, null, htmlAttributes: new { @class = "form-control", @placeholder = "Country" })
                    @Html.ValidationMessageFor(model => model.CountryId, validationMessage: null, htmlAttributes: new { @class = "text-danger" })
                </div>
            </div>
        </div>        
        <div class="row">
            <div class="col-lg-6">
                <div class="form-group @Html.FormControlValidatorClassFor(model => model.Description)">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label" })
                    @Html.TextBoxFor(model => model.Description, htmlAttributes: new { @class = "form-control", @placeholder = "Description", @autofocus = "" })
                    @Html.ValidationMessageFor(model => model.Description, validationMessage: null, htmlAttributes: new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-2">
                <div class="form-group">
                    <input type="submit" class="btn btn-success btn-lg btn-block" value="Save" />
                </div>
            </div>
        </div>
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RealProperty/Views/Province/Index.cshtml
@model IEnumerable<RealProperty.Domain.Models.Province>

@{
    ViewBag.Title = "Province Listing";
}

@section actions {
    <p>
        <a href="@Url.Action("Create", "Province")" class="btn btn-success btn-block"><i class="icon-pushpin"></i> Create new</a>
    </p>
}

<div class="table-responsive">
    <table class="table table-bordered table-hover display datatable">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(model => model.Description)</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.Description)</td>
                    <td>
                        <a href="@Url.Action("Edit", "Province", new { id = item.ProvinceId })" class="btn btn-default btn-sm"><i class="icon-edit"></i> Edit</a>
                        <a href="@Url.Action("Details", "Province", new { id = item.ProvinceId })" class="btn btn-default btn-sm"><i class="icon-folder-open"></i> Details</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

@section Scripts {
    <script type="text/javascript" src="~/Scripts/theme.js"></script>
}