RealProperty/Controllers/CustomerTypeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RealProperty.Domain.Models;

namespace RealProperty.Controllers
{
    [Authorize(Roles = "Superman")]
    public class CustomerTypeController : Controller
    {
        private RealPropertyContext db = new RealPropertyContext();

        //
        // GET: /CustomerType/

        public ActionResult Index()
        {
            return View(db.CustomerTypes.ToList());
        }

        //
        // GET: /CustomerType/Details/5

        public ActionResult Details(int id = 0)
        {
            CustomerType customertype = db.CustomerTypes.Find(id);
            if (customertype == null)
            {
                return HttpNotFound();
            }
            return View(customertype);
        }

        //
        // GET: /CustomerType/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /CustomerType/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CustomerType customertype)
        {
            if (ModelState.IsValid)
            {
                db.CustomerTypes.Add(customertype);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(customertype);
        }

        //
        // GET: /CustomerType/Edit/5

        public ActionResult Edit(int id = 0)
        {
            CustomerType customertype = db.CustomerTypes.Find(id);
            if (customertype == null)
            {
                return HttpNotFound();
            }
            return View(customertype);
        }

        //
        // POST: /CustomerType/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CustomerType customertype)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customertype).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(customertype);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

RealProperty/Views/CustomerType/Create.cshtml
@using RealProperty.HtmlHelpers;
@model RealProperty.Domain.Models.CustomerType

@{
    ViewBag.Title = "Create Customer Type";
}

@section actions {
    <p>
        <a href="@Url.Action("Index", "CustomerType")" class="btn btn-info btn-block"> <i class="icon-edit"></i> Cancel</a>
    </p>
}

<div class="container">
    @using (Html.BeginForm("Create", "CustomerType", FormMethod.Post, htmlAttributes: new { @class = "form-horizontal", @role = "form" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, message: null, htmlAttributes: new { @class = "alert alert-danger" })

        <div class="row">
            <div class="col-lg-6">
                <div class="form-group @Html.FormControlValidatorClassFor(model => model.Description)">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label" })
                    @Html.TextBoxFor(model => model.Description, htmlAttributes: new { @class = "form-control", @placeholder = "Description", @autofocus = "" })
                    @Html.ValidationMessageFor(model => model.Description, validationMessage: null, htmlAttributes: new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-2">
                <div class="form-group">
                    <input type="submit" class="btn btn-success btn-lg btn-block" value="Save" />
                </div>
            </div>
        </div>
    }

</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RealProperty/Views/CustomerType/Details.cshtml
@model RealProperty.Domain.Models.CustomerType

@{
    ViewBag.Title = "Customer Type Details";
}

@section actions {
    <p>
        <a href="@Url.Action("Index", "CustomerType")" class="btn btn-success btn-block"> <i class="icon-edit"></i> Home</a>
    </p>
}

<div class="container">
    <fieldset disabled>
        <div class="row">
            <div class="col-lg-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label" })
                    @Html.TextBoxFor(model => model.Description, htmlAttributes: new { @class = "form-control" })
                </div>
            </div>
        </div>
    </fieldset>
</div>

RealProperty/Views/CustomerType/Edit.cshtml
@using RealProperty.HtmlHelpers;
@model RealProperty.Domain.Models.CustomerType

@{
    ViewBag.Title = "Edit Customer Type";
}
@section actions {
    <p>
        <a href="@Url.Action("Index", "CustomerType")" class="btn btn-info btn-block"> <i class="icon-edit"></i> Cancel</a>
    </p>
}

<div class="container">
    @using (Html.BeginForm("Edit", "CustomerType", FormMethod.Post, htmlAttributes: new { @class = "form-horizontal", @role = "form" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, message: null, htmlAttributes: new { @class = "alert alert-danger" })

        @Html.HiddenFor(model => model.CustomerTypeId)
        <div class="row">
            <div class="col-lg-6">
                <div class="form-group @Html.FormControlValidatorClassFor(model => model.Description)">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label" })
                    @Html.TextBoxFor(model => model.Description, htmlAttributes: new { @class = "form-control", @placeholder = "Description", @autofocus = "" })
                    @Html.ValidationMessageFor(model => model.Description, validationMessage: null, htmlAttributes: new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-2">
                <div class="form-group">
                    <input type="submit" class="btn btn-success btn-lg btn-block" value="Save" />
                </div>
            </div>
        </div>
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RealProperty/Views/CustomerType/Index.cshtml
@model IEnumerable<RealProperty.Domain.Models.CustomerType>

@{
    ViewBag.Title = "Customer Type Listing";
}

@section actions {
    <p>
        <a href="@Url.Action("Create", "CustomerType")" class="btn btn-success btn-block"><i class="icon-pushpin"></i> Create new</a>
    </p>
}

<div class="table-responsive">
    <table class="table table-bordered table-hover display datatable">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(model => model.Description)</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.Description)</td>
                    <td>
                        <a href="@Url.Action("Edit", "CustomerType", new { id = item.CustomerTypeId })" class="btn btn-default btn-sm"><i class="icon-edit"></i> Edit</a>
                        <a href="@Url.Action("Details", "CustomerType", new { id = item.CustomerTypeId })" class="btn btn-default btn-sm"><i class="icon-folder-open"></i> Details</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

@section Scripts {
    <script type="text/javascript" src="~/Scripts/theme.js"></script>
}